apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - prometheus.yaml
  - grafana.yaml
  - ingress.yaml
  - alertmanager.yaml
  - loki-stack.yaml
  - otel-collector.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: blog-platform

configMapGenerator:
  - name: grafana-dashboard-spring
    files:
      - spring-services.json=grafana-dashboard-spring-services.json
