global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager.monitoring.svc:9093']

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          application: 'prometheus'

  - job_name: 'kubernetes-service-endpoints'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - blog-app
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        action: keep
        regex: .*-service
      - target_label: __metrics_path__
        replacement: /actuator/prometheus
      - source_labels: [__meta_kubernetes_service_name]
        target_label: application
      - source_labels: [__meta_kubernetes_service_name]
        target_label: job
