server:
  port: ${SERVER_PORT:8081}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  
  application:
    name: user-service
  
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://user-db:5432/user_service_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:sonvskt303@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:skes mwnj exgf zbdt}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

jwt:
  secret: ${JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A7134743777217A25432A462D4A404E635266556A586E3272357538782F413F4428472B4B}
  expiration: ${JWT_EXPIRATION:86400000}

app:
  base-url: ${APP_BASE_URL:http://localhost:5173}

services:
  interaction-service:
    url: ${INTERACTION_SERVICE_URL:http://interaction-service:8086}

management:
  endpoints:
    web:
      exposure:
        include: health,info
