apiVersion: apps/v1
kind: Deployment
metadata:
  name: interaction-service
  namespace: blog-app
  labels:
    app: interaction-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interaction-service
  template:
    metadata:
      labels:
        app: interaction-service
        tier: backend
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      dnsConfig:
        options:
          - name: ndots
            value: "2"
      containers:
        - name: interaction-service
          image: registry.gitlab.com/mquangpham575/devops/interaction-service:latest
          ports:
            - containerPort: 8086
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SERVER_PORT
              value: "8086"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://interaction-db:5432/interaction_service_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: JWT_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_EXPIRATION
            - name: USER_SERVICE_URL
              value: http://user-service:8081
            - name: BLOG_SERVICE_URL
              value: http://blog-service:8082
          readinessProbe:
            tcpSocket:
              port: 8086
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8086
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
