apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: blog-app
  labels:
    app: blog-service
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: blog-service
