apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  namespace: blog-app
  labels:
    app: customer-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
        tier: backend
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      dnsConfig:
        options:
          - name: ndots
            value: "2"
      containers:
        - name: customer-service
          image: registry.gitlab.com/mquangpham575/devops/customer-service:latest
          ports:
            - containerPort: 8087
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SERVER_PORT
              value: "8087"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://customer-db:5432/customer_service_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: JWT_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_EXPIRATION
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8087
            initialDelaySeconds: 60
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8087
            initialDelaySeconds: 90
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
