apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: customer-db-pvc
  namespace: blog-app
  labels:
    app: customer-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
