apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
  namespace: blog-app
  labels:
    app: file-service
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
        tier: backend
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: file-service
          image: registry.gitlab.com/mquangpham575/devops/file-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SERVER_PORT
              value: "8083"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://file-db:5432/file_service_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD
            - name: SEAWEEDFS_MASTER_URL
              value: http://seaweedfs-master:9333
            - name: SEAWEEDFS_FILER_URL
              value: http://seaweedfs-filer:8888
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: JWT_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_EXPIRATION
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 120
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8083
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
