# ArgoCD AppProject — scopes access for the blog platform
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: blog-platform
  namespace: argocd
spec:
  description: Blog Platform DevOps Project
  sourceRepos:
    - https://gitlab.com/mquangpham575/DevOps.git
  destinations:
    - namespace: blog-app
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
