apiVersion: v1
kind: Service
metadata:
  name: seaweedfs-master
  namespace: blog-app
  labels:
    app: seaweedfs-master
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9333
      targetPort: 9333
    - name: grpc
      port: 19333
      targetPort: 19333
  selector:
    app: seaweedfs-master
