apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seaweedfs-master-pvc
  namespace: blog-app
  labels:
    app: seaweedfs-master
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seaweedfs-volume-pvc
  namespace: blog-app
  labels:
    app: seaweedfs-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
