apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

  # Core

  # Databases

  # SeaweedFS (object storage)

  # Backend services

  # Frontend
resources:
- namespace.yaml
- user-service/deployment.yaml
- user-service/service.yaml
- blog-service/deployment.yaml
- blog-service/service.yaml
- file-service/deployment.yaml
- file-service/service.yaml
- customer-service/deployment.yaml
- customer-service/service.yaml
- interaction-service/deployment.yaml
- interaction-service/service.yaml
- frontend/deployment.yaml
- frontend/configmap.yaml
- frontend/service.yaml
- frontend/ingress.yaml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: blog-platform

# This section is automatically updated by GitLab CI
images:
- name: registry.gitlab.com/mquangpham575/devops/blog-service
  newName: registry.gitlab.com/mquangpham575/devops/blog-service
  newTag: 147f1bb4
- name: registry.gitlab.com/mquangpham575/devops/customer-service
  newName: registry.gitlab.com/mquangpham575/devops/customer-service
  newTag: 88ded220
- name: registry.gitlab.com/mquangpham575/devops/file-service
  newName: registry.gitlab.com/mquangpham575/devops/file-service
  newTag: 88ded220
- name: registry.gitlab.com/mquangpham575/devops/frontend
  newName: registry.gitlab.com/mquangpham575/devops/frontend
  newTag: b9b03623
- name: registry.gitlab.com/mquangpham575/devops/interaction-service
  newName: registry.gitlab.com/mquangpham575/devops/interaction-service
  newTag: 88ded220
- name: registry.gitlab.com/mquangpham575/devops/user-service
  newName: registry.gitlab.com/mquangpham575/devops/user-service
  newTag: 88ded220
